version: "3.4"

services:
  web:
    build: .
    image: web:latest
    container_name: web
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=homework_dev
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    links:
      - db
    depends_on: 
      - db

  db:
      # We use the predefined Postgres image
      image: postgres:10.4
      container_name: db
      ports:
        - "5432:5432"
      environment:
        # Set user/password for Postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DATABASE: homework_dev
        # Set a path where Postgres should store the data
        PGDATA: /var/lib/postgresql/data/pgdata
      restart: always
      volumes:
        - .:/app/

  test:
    image: web:latest
    container_name: test
    environment:
      - MIX_ENV=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=homework_test
      - POSTGRES_HOST=db
    volumes:
      - .:/app/
    links:
      - db
    depends_on: 
      - db
