version: "3.4"

services:
  web:
    build: .
    image: web:latest
    container_name: web
    entrypoint: /app/entrypoint.sh
    ports:
      - "4000:4000"
    environment:
      - FLY_APP_NAME=divvy-web-homework
      - MIX_ENV=dev
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=homework_dev
    # volumes:
    #   - ./config:/app/config
    #   - ./lib:/app/lib
    #   - ./priv:/app/priv
    #   - ./rel:/app/rel
    #   - ./test:/app/test
    #   - ./mix.exs:/app/mix.exs
    #   - ./mix.lock:/app/mix.lock
    links:
      - db
    depends_on:
      - db

  db:
    # We use the predefined Postgres image
    image: postgres:10.4
    container_name: db
    ports:
      - "5432:5432"
    environment:
      # Set user/password for Postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=homework_dev
      # Set a path where Postgres should store the data
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
